import './globals.css'
import 'bootstrap/dist/css/bootstrap.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Link href="/"> 홈 </Link>
        <Link href="/list"> 리스트 </Link> */}
        {children}
      </body>
    </html>
  )
}
